### ISSUE TITLE
Change preview format description in readme

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/themes#10]
_"Images should all be in PNG format, and 225 x 128 pixels in size, except the optional background image(s)"_

Previews can be anything they are scaled in UI to 225 x128. Although to make simple I'd recommend using 480x272 PNG.
BTW good quality 1:1 full screen preview will be then possible if implemented in Theme settings

**Comment by pfeerick** [comment]
Agreed... but also no bigger than 480x272... since *anything* is a stretch to say the least... since the larger the image, the longer it takes the MCU to do the conversion, and thus the less responsive the radio between selecting different images and entering the screen setup menu.
