### ISSUE TITLE
D.Va Pink missing the background image

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/themes#24]
@MuninnFPV Your theme seems do not have the background file.

**Comment by pfeerick** [comment]
Actually, no it is there... there's no logo/banner image ;) i.e. The background is named as the logo/banner image  ... Nice catch... now I know what bugged me when I merged it! 😆

**Comment by richardclli** [comment]
So, what is missing is the logo/banner instead.  And not support for NV14, ha.

**Comment by pfeerick** [comment]
Well, NV14 bg is optional, but yes, background needs renaming, and needs a logo/banner of some sort ;)

**Comment by pfeerick** [comment]
@MuninnFPV Just bumping this 

- [ ] ` DVA_PINK.png` needs renaming to `DVA_PINK_bg_480x272.png`
- [ ] logo/banner made as `DVA_PINK.png` (can also be 480x272 res as will be resized as needed)

**Comment by MuninnFPV** [comment]
I'm sorry 😂 for the life of me I cannot figure out how to rename that file. I'm very new to Github lol

**Comment by pfeerick** [comment]
If you do another PR with the logo/banner, I can do it... it looks you can't rename/edit images through the github web UI - only through `git` or some other GUI frontend...
