### ISSUE TITLE
unable to choose any theme other than default

### ISSUE THREAD

**Issue by QUADMAN7** [EdgeTX/themes#31]
Hello all,
I recently got a TX16s and my first instinct was to flash it with EdgeTX so i did. I just have one issue (i think) with it and that is that i can only choose the default EdgeTX theme. 
![IMG_20220125_195053 1](https://user-images.githubusercontent.com/74206621/151049711-86b623ba-9e57-444d-b636-d43fff06a964.jpg)
When i press the telemetry key on the TX16s to go to the user interface screen to select another theme there is only the one 'EdgeTX Default' theme to choose from. i have looked on the SD card and there are other  themes on it but i am unable to select them. This also makes me beg the question how do you import your own splash screens and model pictures??
Any help would be greatly appreciated

Just on a side note, i was wondering if edgeTX is suppose to say "welcome to edgeTX" when you turn the radio on like opentx did because my radio doesn't.

**Comment by pfeerick** [comment]
This sounds like you don't have the SD card pack correctly installed... for themes you could have the wrong version, but for the welcome to edgetx to be missing it sounds like the folder structure is messed up. 

What version of EdgeTX did you flash? And what does your THEMES directory look like?

**Comment by QUADMAN7** [comment]
I followed Joshua Bardwell's video on installing EdgeTX. I have flashed version 2.5.0 . I'm not sure what you mean by Themes directory but I have attached a picture which might show it. 
![IMG_20220126_161204 1](https://user-images.githubusercontent.com/74206621/151201744-2899f66e-dd90-4dcb-897b-749a3658cf87.jpg)

**Comment by pfeerick** [comment]
You have the wrong themes directory structure for v2.5 - you should not have folders for each theme - that is the directory structure for v2.6 ;)

Get the zip from [here](https://github.com/EdgeTX/themes/archive/refs/heads/2.5.zip) and replace the THEMES directory on your SD card with the one from that zip file. 

For your custom splash screen, same as it was with OpenTX = `/IMAGE/splash.png`

**Comment by pfeerick** [comment]
Can I get another look at your THEMES directory to see what it looks like now?

And if you mean the background (splash screen is what is shown when the transmitter first turns on)... that is probably also related to something wrong in THEMES directory again.

**Comment by QUADMAN7** [comment]
Here are the photo's. I looked though the theme's directory and did not see an EdgeTX themes folder. would it be easier just to reflsh edgeTX??
![IMG_20220128_170057 1](https://user-images.githubusercontent.com/74206621/151591481-37c973d6-2c4d-4973-95b0-4ea181358799.jpg)
![IMG_20220128_170106 1](https://user-images.githubusercontent.com/74206621/151591513-0dcd8211-268a-4c31-8340-01ca20a4e233.jpg)

**Comment by pfeerick** [comment]
Ok, that's not right at all. I said to "replace the THEMES directory (aka folder) on your SD card with the one from that zip file." ;) 

1) Get the SD card pack from here -> https://github.com/EdgeTX/edgetx-sdcard/releases/download/v2.5.0/horus.zip

2) Copy the contents of the zip file to your SD card. The root of your SD card should now look something like this:
![image](https://user-images.githubusercontent.com/5500713/151639199-2716b448-a0d0-40bb-b44a-bca24500f1b9.png)

3) When you go into the THEMES folder, it should look like this:
![image](https://user-images.githubusercontent.com/5500713/151639207-87bcbd98-c7f5-4ab3-8b21-3488171fb326.png)

4) If you want the themes from the THEMES directory as well, using the [zip mentioned earlier](https://github.com/EdgeTX/themes/archive/refs/heads/2.5.zip), and add the contents of the THEMES directory from that zip file to the THEMES folder on your SD card. The THEMES folder on your SD card should now look like this:

![image](https://user-images.githubusercontent.com/5500713/151639690-6e5085b2-a795-4c9a-9ecd-01165d000289.png)

**Comment by QUADMAN7** [comment]
Thank you very much for your help, it worked like a charm!!!!! Just one more thing though, is the radio mmeant to say "Welcome to EdgeTX" when you power it up because mine doesn't.
THANKS FOR THE HELP!!!!!!!!!!!!!!!!!!!

**Comment by pfeerick** [comment]
Yup. That means you probably don't have the sound pack on your SD card. If you want the English one, you want 

https://github.com/EdgeTX/edgetx-sdcard-sounds/releases/download/latest/edgetx-sdcard-sounds-en-2.5.4.zip

(otherwise pick your language from the list at https://github.com/EdgeTX/edgetx-sdcard-sounds/releases)

Put the SOUNDS folder in that zip in the root of your SD card also. If you did it right you should be able to go into the SOUNDS folder of your SD card and see the 'en' folder.

**Comment by QUADMAN7** [comment]
Thanks for all the help!! everything is working fine now (i think).

**Comment by pfeerick** [comment]
No problem. Have fun! :)
