### ISSUE TITLE
Can't use custom theme background.png in EdgeTX 2.6

### ISSUE THREAD

**Issue by Verix** [EdgeTX/themes#32]
Whenever you use a customized theme other than the default theme, the space where it's supposed to be background.png is filled by one of the theme colors. Likely to be Secondary3
![43b744508fd58d660e66cea7feac954](https://user-images.githubusercontent.com/1698987/151063346-df4c33cd-859f-495d-a5a9-6304e6b4e21c.jpg)
.

**Comment by pfeerick** [comment]
You need to use the correct filename for background images for custom themes. It also seems like there is an issue with global background not being sourced if theme background not present (until the radio is rebooted, that is). 

Per the readme:

- themename/background_480x272.png (a background image for your theme in 480 x 272 pixel resolution, e.g. for TX16S, T16, X10, X12S)
- themename/background_320x480.png (a background image for your theme in 320 x 480 pixel resolution, e.g. for NV14)

**Comment by pfeerick** [comment]
Closing as a temporary fix is in place via https://github.com/EdgeTX/edgetx/pull/1684, will a more complete implementation proposed for 2.8 via https://github.com/EdgeTX/edgetx/issues/1681
