### ISSUE TITLE
background issue with themes that comes with SD content (2.5.4) 

### ISSUE THREAD

**Issue by Daannoa** [EdgeTX/themes#33]
Hello,
I just updated my radio to edgeTX 2.6.0, and I notice a strange thing with themes:
If I select one of the default themes (FM2M themes) that comes with SD content (2.5.4) I shouldn't get a background but when I restart the radio the background.png from the "EdgeTX" theme applies.

The only workaround i found is to rename the background.png of the EdgTX theme but this solution is not very clean.

I think if the themes don't contain a background.png file then no background should be applied.

**Comment by Daannoa** [comment]
Theme used for the test:
![IMG_3468](https://user-images.githubusercontent.com/93767482/151237520-c2860b12-3932-4fe3-a5ed-a1b72a559bec.jpeg)

before restarting the radio:
![IMG_3470](https://user-images.githubusercontent.com/93767482/151237785-a473c94c-fd23-492b-bce7-381d9e05601e.jpeg)

after restarting the radio:
![IMG_3471](https://user-images.githubusercontent.com/93767482/151237862-7770dff3-7eeb-4b72-877c-ac2f84e74099.jpeg)

**Comment by pfeerick** [comment]
This related to  #32. 

What *should* be happening (but probably just isn't being refreshed in the right order) at present is if the theme provides it's own background, it is used. If not, the global background is used. At the moment the global default is the `EdgeTX\background.png` for legacy reasons... that should change to `IMAGES\background.png` IMO.

However, I also think that the order of priority should be:
1. model
2. theme
3. global

For 2 though, we really need a user option, probably in the model settings, thus allowing 1 to be custom name, as you can't just make the assumption that if a theme doesn't come with a background, that the fill colour should be used. As that then requires the user to fiddle with background_480x272.png or background_320x480.png files in the theme folder if they actually want a background image.

**Comment by pfeerick** [comment]
Closing as a temporary fix is in place via https://github.com/EdgeTX/edgetx/pull/1684, will a more complete implementation proposed for 2.8 via https://github.com/EdgeTX/edgetx/issues/1681
