### ISSUE TITLE
Themes to monocrome (black and white)

### ISSUE THREAD

**Issue by ThePhantom05** [EdgeTX/themes#49]
Hello) Dear developers) Tell me, are themes created only for radiomaster x16 (color screen)? On black and white (monochrome) Taranis x9D+ screens, this is possible

**Comment by pfeerick** [comment]
No, there is no facility for theming on B&W radios - only radios with color screens. Because, you know, B&W screens don't show color, and that is all the themes control ;)

**Comment by pfeerick** [comment]
You can customise the splash screen on B&W screen radios, which you do using the `Settings => Edit Radio Splash Image...` option of Companion to customise the splash screen image that is embedded in the radio firmware.
